name: Release to mainnet with IDL and verify

on:
  workflow_dispatch:
    inputs:
      priority_fee:
        description: "Priority fee for transactions"
        required: true
        default: "300000"
        type: string

jobs:
  build:
    uses: solana-developers/github-workflows/.github/workflows/reusable-build.yaml@v0.3.3
    with:
      program: "workflow_tutorial"
      program-id: "wocur7QRRMdzPZN52688gBa5iJD4mLkNWSxN5xGGRjY"
      network: "mainnet"
      deploy: true
      upload_idl: true
      verify: true
      use-squads: true
      use-program-metadata-idl: true
      override-solana-version: "3.1.10"
      override-anchor-version: "1.0.1"
      priority-fee: ${{ github.event.inputs.priority_fee }}

    secrets:
      MAINNET_SOLANA_DEPLOY_URL: ${{ secrets.MAINNET_SOLANA_DEPLOY_URL }}
      MAINNET_DEPLOYER_KEYPAIR: ${{ secrets.MAINNET_DEPLOYER_KEYPAIR }}
      PROGRAM_ADDRESS_KEYPAIR: ${{ secrets.PROGRAM_ADDRESS_KEYPAIR }}
      MAINNET_MULTISIG: ${{ secrets.MAINNET_MULTISIG }}
      MAINNET_MULTISIG_VAULT: ${{ secrets.MAINNET_MULTISIG_VAULT }}
